### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by overheadhunter** [skymatic/appstore-reverse-charger#1]
`de.skymatic.app` isn't a good package name. Use `de.skymatic.appbills` or something similar.

@tobihagemann any ideas for a name? Maybe even for a product name? I consider `appstore-reverse-charger` only the working title.

**Comment by infeo** [comment]
I agree with you, the identifier should be more specific. Since this package contains the gui, i would rename it to `de.skymatic.gui`. But this is also quite generic.

Maybe the main class should be outsourced in an extra package? This would also be beneficial in combination with the module system, since then really _only_ the main class is accessible from the outside.

**Comment by overheadhunter** [comment]
It is not the Skymatic GUI, is it? 

Follow the `vendor.product.component` scheme.

I don't mind, if you add "gui" (even though [I prefer vertically sliced package names](https://softwareengineering.stackexchange.com/q/338597)), but _please add an application name_!

**Comment by infeo** [comment]
For a good name we can open a new issue, right now i just renamed it to fit into the suggested scheme.
